#!/bin/sh
nitrogen --restore
pkill polybar; polybar &


pkill sxhkd; sxhkd &
pkill picom; picom &
pkill dunst; dunst &
pkill clipit; clipit &
easyeffects --gapplication-service -w &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config window_gap            -1
bspc config border_width           1
bspc config top_padding            1
bspc config bottom_padding        33
bspc config left_padding           1
bspc config right_padding          1
bspc config focused_border_color "#d8a657"
bspc config normal_border_color  "#32302f"

xsetroot -cursor_name left_ptr
xset -dpms s off

xdo above -N "Polybar" -t $(xdo id -N Bspwm -n root)
