#!/bin/sh

pkill sxhkd; sxhkd &
pkill picom; picom &
pkill dunst; dunst &
pkill clipit; clipit &
pkill polybar; polybar &
easyeffects --gapplication-service -w &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config window_gap           32
bspc config border_width         0 
i=2
bspc config top_padding          $((32+$i))
bspc config bottom_padding       $i
bspc config left_padding         $i
bspc config right_padding        $i
bspc config focused_border_color "#89b482"
bspc config normal_border_color  "#292828"
